### ISSUE TITLE
Node AND Npm on ms-iot (Raspberry Pi) to support PXT

### ISSUE THREAD

**Issue by OwenBrotherwood** [ms-iot/node#13]
Hej
I have a node working  on a Pi, but now I have to figure out how to get npm/gyp over.
The issue is bookmarked at PXT: but I think the actual help could be found "here"
Please see the issue for the details @ https://github.com/Microsoft/pxt/issues/581
The main meat is @ https://github.com/Microsoft/pxt/issues/581#issuecomment-256339044

**Comment by OwenBrotherwood** [comment]
npm seems to be ok with the following: 
compile node and then save on Rasperry Pi
add path to node (
download npm from https://github.com/npm/npm
node node_modules\npm\cli.js install -g npm # doing just now

so only a working gyp needed ...

**Comment by OwenBrotherwood** [comment]
OK: a little more "progress"...
In Visual Studio 2015, with installation support for node in universal windows, there is a hello world example.
It is possible to run remote to the Pi: "Hello world"
Add serialport to the npm, the run remote dies with:
`The program '[1196] backgroundTaskHost.exe' has exited with code 1 (0x1).`
Not much to go on yet: I have to start doing serious work: but does make a nice scenario for tests as an IoT device without a serialport support is "strange" if one would like to use node.

**Comment by IoTGirl** [comment]
Hi Munyiri and Paul,
Could one of you please review this issue request?
Sincere thanks,
IoTGirl

**Comment by munyirik** [comment]
Hi @OwenBrotherwood, sorry this issue fell under the radar. Are you still having an issue with serialport?

**Comment by munyirik** [comment]
Also did you mention serialport because PXT is using it? (I'm not really familiar with PXT)

**Comment by munyirik** [comment]
Closing for now. Feel free to re-open if you still have issues.

**Comment by OwenBrotherwood** [comment]
That is ok @munyirik
I was wanting to reply, but at the time, I was involved in "something else" and was unable to give time to create a good reply.
yes: PXT is using serialport

**Comment by IoTGirl** [comment]
@OwenBrotherwood You did not re-open so we are assuming you are no longer having issues.
